"""Gate 9: time-ordered operator paths and Lie-bracket memory.

A fixed matrix generates a flow. A moving matrix generates a time-ordered
product. If successive generators do not commute, the path can matter even
when first-order exposure sums to zero.

This gate deliberately starts below "learning". It asks whether the moving
operator trajectory itself has a measurable computational state variable that
is absent from the instantaneous operator and from the time-average.

Two nilpotent shear generators are used:

    H = [[0, 1], [0, 0]]
    V = [[0, 0], [1, 0]]

Their commutator is

    [H, V] = H V - V H = diag(1, -1),

a saddle direction that is not supplied as a primitive.

The closed loop H -> V -> -H -> -V has zero integrated generator, but its
time-ordered exponential is not identity. Reversing the loop flips the
second-order commutator residue. A commuting diagonal control must collapse.

A second assay asks whether a tiny observer can decode signed path area from
the final state on held-out path lengths. This is a mechanism audit, not an
efficiency claim: a digital counter can compute the same toy target exactly.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


@dataclass(frozen=True)
class LiePathConfig:
    epsilon: float = 0.08
    scaling_eps: tuple[float, ...] = (0.01, 0.02, 0.04, 0.08)
    train_loop_counts: tuple[int, ...] = (8, 12, 16)
    test_loop_counts: tuple[int, ...] = (10, 14, 18)
    train_samples: int = 3000
    test_samples: int = 1500
    seeds: int = 6
    ridge: float = 1e-8

    def as_dict(self) -> dict:
        return asdict(self)


def matrix_exponential(A: np.ndarray, terms: int = 40) -> np.ndarray:
    """Small dense matrix exponential by direct Taylor series.

    Gate 9 uses tiny matrices with ||A|| <= 0.08, so this deliberately simple
    implementation is accurate and keeps scipy out of the dependency set.
    """
    A = np.asarray(A, dtype=float)
    out = np.eye(A.shape[0], dtype=float)
    term = np.eye(A.shape[0], dtype=float)
    for k in range(1, terms + 1):
        term = (term @ A) / float(k)
        out = out + term
    return out


def shear_generators() -> tuple[np.ndarray, np.ndarray]:
    H = np.asarray([[0.0, 1.0], [0.0, 0.0]])
    V = np.asarray([[0.0, 0.0], [1.0, 0.0]])
    return H, V


def commuting_generators() -> tuple[np.ndarray, np.ndarray]:
    D1 = np.asarray([[1.0, 0.0], [0.0, 0.0]])
    D2 = np.asarray([[0.0, 0.0], [0.0, 1.0]])
    return D1, D2


def commutator(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    return A @ B - B @ A


def ordered_flow(generators: Iterable[np.ndarray], epsilon: float) -> np.ndarray:
    """Apply exp(epsilon G_1), then exp(epsilon G_2), ... to a column state."""
    U = None
    for G in generators:
        G = np.asarray(G, dtype=float)
        if U is None:
            U = np.eye(G.shape[0], dtype=float)
        U = matrix_exponential(float(epsilon) * G) @ U
    if U is None:
        raise ValueError("ordered_flow requires at least one generator")
    return U


def positive_loop(A: np.ndarray, B: np.ndarray) -> tuple[np.ndarray, ...]:
    return (A, B, -A, -B)


def negative_loop(A: np.ndarray, B: np.ndarray) -> tuple[np.ndarray, ...]:
    return (B, A, -B, -A)


def _alignment(A: np.ndarray, B: np.ndarray) -> float:
    a = np.asarray(A, dtype=float).ravel()
    b = np.asarray(B, dtype=float).ravel()
    return float(abs(a @ b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-15))


def _span_rank(mats: Iterable[np.ndarray], tol: float = 1e-10) -> int:
    rows = [np.asarray(M, dtype=float).ravel() for M in mats]
    if not rows:
        return 0
    return int(np.linalg.matrix_rank(np.stack(rows), tol=tol))


def _add_independent(
    basis: list[np.ndarray],
    candidate: np.ndarray,
    tol: float = 1e-10,
) -> bool:
    candidate = np.asarray(candidate, dtype=float)
    if np.linalg.norm(candidate) <= tol:
        return False
    before = _span_rank(basis, tol)
    after = _span_rank([*basis, candidate], tol)
    if after > before:
        basis.append(candidate.copy())
        return True
    return False


def lie_closure(
    generators: Iterable[np.ndarray],
    max_rounds: int = 8,
    tol: float = 1e-10,
) -> tuple[list[np.ndarray], list[int]]:
    """Return an independent basis for the Lie algebra generated by matrices."""
    basis: list[np.ndarray] = []
    for G in generators:
        _add_independent(basis, np.asarray(G, dtype=float), tol)
    history = [len(basis)]

    for _ in range(max_rounds):
        snapshot = list(basis)
        grew = False
        for A in snapshot:
            for B in snapshot:
                grew |= _add_independent(basis, commutator(A, B), tol)
        if not grew:
            break
        history.append(len(basis))
    return basis, history


def _distance_to_span(target: np.ndarray, basis: Iterable[np.ndarray]) -> float:
    basis = list(basis)
    t = np.asarray(target, dtype=float).ravel()
    if not basis:
        return float(np.linalg.norm(t))
    M = np.stack([np.asarray(B, dtype=float).ravel() for B in basis], axis=1)
    coef, *_ = np.linalg.lstsq(M, t, rcond=None)
    residual = t - M @ coef
    return float(np.linalg.norm(residual) / (np.linalg.norm(t) + 1e-15))


def chain3_generators() -> list[np.ndarray]:
    def E(i: int, j: int) -> np.ndarray:
        M = np.zeros((3, 3), dtype=float)
        M[i, j] = 1.0
        return M

    # Only nearest-neighbor, bidirectional shear primitives.
    return [E(0, 1), E(1, 0), E(1, 2), E(2, 1)]


def _fit_affine(X: np.ndarray, y: np.ndarray, ridge: float) -> np.ndarray:
    X1 = np.column_stack([np.ones(len(X), dtype=float), X])
    gram = X1.T @ X1 + float(ridge) * np.eye(X1.shape[1])
    return np.linalg.solve(gram, X1.T @ y)


def _predict_affine(X: np.ndarray, w: np.ndarray) -> np.ndarray:
    return np.column_stack([np.ones(len(X), dtype=float), X]) @ w


def _path_dataset(
    U_pos: np.ndarray,
    U_neg: np.ndarray,
    loop_counts: tuple[int, ...],
    samples: int,
    seed: int,
) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    z0 = np.asarray([1.0, 0.7], dtype=float)
    X = np.zeros((samples, 2), dtype=float)
    y = np.zeros(samples, dtype=float)

    for i in range(samples):
        n = int(rng.choice(loop_counts))
        signs = rng.choice(np.asarray([-1, 1], dtype=int), size=n)
        z = z0.copy()
        for s in signs:
            z = (U_pos if s > 0 else U_neg) @ z
        X[i] = z
        y[i] = float(np.mean(signs))
    return X, y


def _decoder_seed(
    seed: int,
    U_pos: np.ndarray,
    U_neg: np.ndarray,
    U_pos_commuting: np.ndarray,
    U_neg_commuting: np.ndarray,
    config: LiePathConfig,
) -> dict[str, float]:
    Xtr, ytr = _path_dataset(
        U_pos,
        U_neg,
        config.train_loop_counts,
        config.train_samples,
        10_000 + seed,
    )
    Xte, yte = _path_dataset(
        U_pos,
        U_neg,
        config.test_loop_counts,
        config.test_samples,
        20_000 + seed,
    )
    w = _fit_affine(Xtr, ytr, config.ridge)
    pred = _predict_affine(Xte, w)

    Xtr_c, ytr_c = _path_dataset(
        U_pos_commuting,
        U_neg_commuting,
        config.train_loop_counts,
        config.train_samples,
        30_000 + seed,
    )
    Xte_c, yte_c = _path_dataset(
        U_pos_commuting,
        U_neg_commuting,
        config.test_loop_counts,
        config.test_samples,
        40_000 + seed,
    )
    wc = _fit_affine(Xtr_c, ytr_c, config.ridge)
    pred_c = _predict_affine(Xte_c, wc)

    mse = float(np.mean((pred - yte) ** 2))
    var = float(np.var(yte))
    mse_c = float(np.mean((pred_c - yte_c) ** 2))
    var_c = float(np.var(yte_c))

    corr = float(np.corrcoef(pred, yte)[0, 1])
    # Commuting state is theoretically constant. Correlation can be NaN due to
    # zero predicted variance, so R^2 is the stable control statistic.
    return {
        "correlation": corr,
        "r2": 1.0 - mse / (var + 1e-15),
        "mse": mse,
        "commuting_r2": 1.0 - mse_c / (var_c + 1e-15),
        "commuting_mse": mse_c,
        "target_variance": var,
    }


def _agg(values: Iterable[float]) -> dict[str, float]:
    a = np.asarray(tuple(values), dtype=float)
    return {"mean": float(np.mean(a)), "std": float(np.std(a))}


def run_battery(config: LiePathConfig | None = None) -> dict:
    c = config or LiePathConfig()
    H, V = shear_generators()
    D1, D2 = commuting_generators()

    U_pos = ordered_flow(positive_loop(H, V), c.epsilon)
    U_neg = ordered_flow(negative_loop(H, V), c.epsilon)
    U_pos_c = ordered_flow(positive_loop(D1, D2), c.epsilon)
    U_neg_c = ordered_flow(negative_loop(D1, D2), c.epsilon)

    I2 = np.eye(2)
    bracket = commutator(H, V)
    delta = U_pos - U_neg

    # Both loops have zero first-order integrated generator by construction.
    net_exposure = H + V - H - V

    residues = []
    for eps in c.scaling_eps:
        U = ordered_flow(positive_loop(H, V), eps)
        residues.append(float(np.linalg.norm(U - I2)))
    slope = float(
        np.polyfit(np.log(np.asarray(c.scaling_eps)), np.log(np.asarray(residues)), 1)[0]
    )

    decoder_rows = [
        _decoder_seed(
            seed,
            U_pos,
            U_neg,
            U_pos_c,
            U_neg_c,
            c,
        )
        for seed in range(c.seeds)
    ]

    closure2, history2 = lie_closure([H, V])
    chain3 = chain3_generators()
    closure3, history3 = lie_closure(chain3)
    E13 = np.zeros((3, 3), dtype=float)
    E13[0, 2] = 1.0

    return {
        "config": c.as_dict(),
        "closed_loop": {
            "net_exposure_norm": float(np.linalg.norm(net_exposure)),
            "positive_residue_norm": float(np.linalg.norm(U_pos - I2)),
            "negative_residue_norm": float(np.linalg.norm(U_neg - I2)),
            "commuting_positive_residue_norm": float(np.linalg.norm(U_pos_c - I2)),
            "commuting_negative_residue_norm": float(np.linalg.norm(U_neg_c - I2)),
            "reverse_difference_commutator_alignment": _alignment(delta, bracket),
            "epsilon_scaling_slope": slope,
            "commutator": bracket.tolist(),
            "positive_flow": U_pos.tolist(),
            "negative_flow": U_neg.tolist(),
        },
        "held_out_path_decoder": {
            "correlation": _agg(row["correlation"] for row in decoder_rows),
            "r2": _agg(row["r2"] for row in decoder_rows),
            "mse": _agg(row["mse"] for row in decoder_rows),
            "commuting_r2": _agg(row["commuting_r2"] for row in decoder_rows),
            "commuting_mse": _agg(row["commuting_mse"] for row in decoder_rows),
            "target_variance": _agg(row["target_variance"] for row in decoder_rows),
            "observer_features": 2,
            "digital_counter_exact": True,
        },
        "lie_closure": {
            "two_state_primitive_dimension": 2,
            "two_state_closure_dimension": len(closure2),
            "two_state_history": history2,
            "three_state_primitive_dimension": len(chain3),
            "three_state_closure_dimension": len(closure3),
            "three_state_history": history3,
            "E13_distance_to_primitive_span": _distance_to_span(E13, chain3),
            "E13_distance_to_closure_span": _distance_to_span(E13, closure3),
            "full_sl3_dimension": 8,
        },
    }


def write_json(path: str | Path, payload: dict) -> None:
    import json

    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
